services:
  app:
    image: 'spring-boot-rest-service/car-rest-service-docker:latest'
    container_name: car-app
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/car_database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_JPA_GENERATE_DDL=true
      - SPRING_SQL_INIT_MODE=never
      - CSV_IMPORT_ENABLED=false

  db:
    image: 'postgres:17'
    container_name: car-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=car_database